version: "3.8"
name: valytics
services:
  riot-ingest:
    build:
      context: ./
      dockerfile: ./services/riot-ingest/Dockerfile
    volumes:
      - ./services/riot-ingest:/service
      - ./protobufs:/protobufs
    env_file:
      - .env
    command: watchmedo auto-restart --recursive --pattern="*.py" --directory="/service/" python3 /service/src/main/service.py
    profiles:
      - backend

  python-lint:
    build:
      context: ./
      dockerfile: ./builder/python-lint/Dockerfile
    volumes:
    - ./services:/services
    profiles:
      - pre-commit
    command: 
      - /bin/bash
      - -c
      - |
        black --version
        black --line-length 120 /services
        flake8 --version
        flake8 /services
