version: "3.8"
name: valytics
services:
  ###
  # Service Containers
  ###
  riot-ingest:
    build:
      context: ./
      dockerfile: ./services/riot-ingest/Dockerfile
    env_file:
      - .env
    volumes:
      - ./services/riot-ingest/src/main:/service
      - ./protobufs:/protobufs
    command: watchmedo auto-restart --recursive --pattern="*.py" --directory="/service/" python3 /service/service.py
    profiles:
      - backend
    networks:
      - valyticsmesh

  ###
  # Test Containers
  ###
  integration:
    build:
      context: ./
      dockerfile: ./containers/integration-test/Dockerfile
    env_file:
      - .env
    volumes:
      - ./services/riot-ingest/src/test:/tests/riot-ingest
      - ./protobufs:/protobufs
    command: pytest /tests
    profiles:
      - test
    networks:
      - valyticsmesh

  python-lint:
    build:
      context: ./
      dockerfile: ./containers/python-lint/Dockerfile
    volumes:
    - ./services:/services
    command: 
      - /bin/bash
      - -c
      - |
        black --version
        black --line-length 120 /services
        flake8 --version
        flake8 /services
    profiles: [ "pre-commit", "pylint" ]
    network_mode: none

  ###
  # Envoy and API stats
  ###
  api-gateway:
    build:
      context: ./
      dockerfile: ./containers/api-gateway/Dockerfile
      args:
        RIOT_INGEST_SERVICE_PORT: ${RIOT_INGEST_SERVICE_PORT}
    env_file:
      - .env
    depends_on:
      - riot-ingest
      - statsd-exporter
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.json -l trace --log-path /tmp/envoy-info.log
    profiles:
      - backend
    ports:
      - ${HOST}:${ENVOY_EDGE_GATEWAY_PORT}:8080
      - ${HOST}:${ENVOY_EDGE_GATEWAY_ADMIN_PORT}:9090
    networks:
      - valyticsmesh

  statsd-exporter:
    image: prom/statsd-exporter:latest
    profiles:
      - backend
    networks:
      - valyticsmesh

  prometheus:
    build:
      context: ./
      dockerfile: ./containers/prometheus/Dockerfile
    depends_on:
      - statsd-exporter
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    profiles:
      - backend
    ports:
      - ${HOST}:${PROMETHEUS_PORT}:9090
    networks:
      - valyticsmesh


networks:
  valyticsmesh:
    driver: bridge
    name: valyticsmesh