version: "3.8"
name: valytics
services:
  riot-ingest:
    build:
      context: ./
      dockerfile: ./services/riot-ingest/Dockerfile
    volumes:
      - ./services/riot-ingest:/service
      - ./protobufs:/protobufs
    env_file:
      - .env
    ports:
      - ${RIOT_INGEST_SERVICE_PORT}:${RIOT_INGEST_SERVICE_PORT}
    command: watchmedo auto-restart --recursive --pattern="*.py" --directory="/service/" python3 /service/src/main/service.py
    profiles:
      - backend
    networks:
      valyticsmesh:
        ipv4_address: 172.199.0.3

  riot-ingest-test:
    build:
      context: ./
      dockerfile: ./services/riot-ingest/Dockerfile
    volumes:
      - ./services/riot-ingest:/service
      - ./protobufs:/protobufs
    env_file:
      - .env
    command: python3 /service/src/test/service_test_client.py
    profiles:
      - test
    networks:
      valyticsmesh:
        ipv4_address: 172.199.0.4

  python-lint:
    build:
      context: ./
      dockerfile: ./builder/python-lint/Dockerfile
    volumes:
    - ./services:/services
    profiles:
      - pre-commit
    command: 
      - /bin/bash
      - -c
      - |
        black --version
        black --line-length 120 /services
        flake8 --version
        flake8 /services
    networks:
      - valyticsdev

networks:
  valyticsdev:
    driver: bridge
  valyticsmesh:
    driver: bridge
    ipam:
      config:
      - subnet: 172.199.0.0/16
      driver: default
    name: valyticsmesh