FROM mockserver/mockserver:latest

ENV MOCKSERVER_INITIALIZATION_JSON_PATH /etc/mockserver/mockserver-config.json

COPY containers/etc/mock-server/mockserver-config.json /etc/mockserver/mockserver-config.json
