# Use the mockserver/mockserver base image
FROM mockserver/mockserver

# Copy the custom configuration file into the container
COPY containers/mock-server/mockserver-config.json /mockserver/mockserver-config.json
